In [3]:
import numpy as np

def array_factory(mode, shape, value=None):
    if mode == 'zeros':
        return np.zeros(shape)
        
    elif mode == 'ones':
        return np.ones(shape)
        
    elif mode == 'full':
        return np.full(shape, value)
        
    elif mode == 'identity':
        return np.identity(shape)

print("Zeros Array:")
print(array_factory('zeros', (2, 2)))

print("\nOnes Array:")
print(array_factory('ones', (3, 3)))

print("\nFull Array (with value 5):")
print(array_factory('full', (2, 3), value=5))

print("\nIdentity Matrix:")
print(array_factory('identity', 3))

Zeros Array:
[[0. 0.]
 [0. 0.]]

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full Array (with value 5):
[[5 5 5]
 [5 5 5]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
def secure_reshape_and_stack(data1, data2, new_shape):
    try:

        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape)

        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")



# بيانات تجريبية
data_a = [1, 2, 3, 4, 5, 6]      
data_b = [[7, 8, 9], [10, 11, 12]] 

new_shape = (2, 3)

result = secure_reshape_and_stack(data_a, data_b, new_shape)

print("Combined Dataset:")
print(result)

Combined Dataset:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    arr = np.array(arr)
    
    condition = arr >= threshold
    
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr

branch_a = [1, 2, 3, 4, 5, 6]
branch_b = [[7, 8, 9],
            [10, 11, 12]]
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print(final_report)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
